### PR TITLE
PCB schematic and microcontroller code

### PR DESCRIPTION
**Pull request by phenidone**
The schematic is probably about right, and there is draft code for an STM32F030 which is capable of reading sensors, storing values over time and then batch-downloading them to a Pi.

In a soon-future revision, it will switch the Pi on/off (e.g. initiate a transfer if an observation varies outside bounds) and be controllable over its serial port.

### CODE REVIEW

**Comment by matthewberryman** [comment]
@phenidone can you please change https://github.com/phenidone/cognicity-floodsensor/blob/master/micro/src/flood.cpp#L89 to leave the time in ms? The rest of our code uses ms (because that's how js handles things) up until we convert to time in s before plonking it in the database in https://github.com/smart-facility/cognicity-floodsensor/blob/master/lambda/index.js#L28

**Comment by phenidone** [comment]
Reporting milliseconds is easy, as long as you're aware that there is nowhere near that much precision in the timing.  

Firstly, making a complete observation takes at least 200ms (median of up to 5 ultrasonic ranges) and up to 10s if the DHT22 needs a few retries in order to wake up and/or gives checksum issues.

Secondly, the clock source is the internal RC oscillator at the moment, which has only 1% accuracy.
In future - once the PCB is debugged and ST release the CMSIS for it - we can swap the STM32F030 for an STM32L031 which includes RTC support with an external 32768Hz crystal, which should give you 20ppm.

You'll need to ask the micro what it thinks the time is at the beginning of each dump (hourly?) and do a linear interpolation to map between the micro's timestamps and NTP time, assuming you're on NTP.

**Comment by phenidone** [comment]
PS storing ms means expanding an observation from 10 bytes to 14 in order to fit the 64-bit value.  That means storing about 2 hours of samples (at 1 minute period) instead of 3 hours.

Or I could store seconds and report whole seconds to you *1000.

**Comment by phenidone** [comment]
STM32 code is now feature-complete, README added for the STM32.

**Comment by matthewberryman** [comment]
I think having it every 2 hours is fine (and if necessary, can always change it back and do the conversion on the pi), and I'm not too worried about accuracy—drift we can correct for using NTP, and the delays in taking measurements are fine, although it might be an idea to re-order so that the DHT is taken first (as that's highly variable), then the HC-SR04, and then record the obs.when after that. The real key thing at any rate is to have wake up if threshold is exceeded and we have that now (thanks!)

**Comment by phenidone** [comment]
PCB is ready for eyeballing and could probably be manufactured at this point.  Let me know what you think, especially if you want to change labelling/branding etc.

There is a pcb/plot subdirectory with gerbers, so you can view the layout without needing to have a copy of kicad.

**Comment by matthewberryman** [comment]
Tested and working great, so closing this pull request. Looking forward to getting the hats. Thanks @phenidone cc @talltom 
img_2012

**Comment by matthewberryman** [comment]
Whoops forgot to merge first

**Pull request merged**
